<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-E36DAG2Q" name="Default test(failed)(failed)" tests="2" failures="2" timestamp="26 Feb 2020 14:01:50 GMT" time="0.037" errors="0">
  <testcase name="login4" time="0.006" classname="pack3.Failing">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at pack3.Failing.login4(Failing.java:21)
	at pack3.RunFailedTestCase.main(RunFailedTestCase.java:15)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- login4 -->
  <testcase name="login1" time="0.0" classname="pack3.Failing">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at pack3.Failing.login1(Failing.java:9)
	at pack3.RunFailedTestCase.main(RunFailedTestCase.java:15)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- login1 -->
</testsuite> <!-- Default test(failed)(failed) -->
